name = "aiken-lang/mpx-token"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/mpx-token'"

[repository]
user = "aiken-lang"
project = "mpx-token"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
